### ISSUE TITLE
Is this still actively maintained?

### ISSUE THREAD

**Issue by ftjuh** [waspinator/AccelStepper#15]
Latest release to the library manager is v1.61 from 2020-06-30.

Latest AccelStepper version is v1.63 from  2022-06-30.

It would be nice to be able to install it from the library manager.

Thanks for your effort
Jan

**Comment by StefanL38** [comment]
Hi ftjuh,

in my humble opinion the stepper-library MobaTools is much better than AccelStepper.
The MobaTools-library can be installed from the library-manager
and it offers non-blocking step-pulse-creation "In the backround"
With AccelStepper you have to accept one of two disadvantages:

disadvantage 1: driving the stepper-motor in a blocking way which means nothing else than driving the steppermotor can be done as long as the motor runs

disadvantage 2: keeping your main-loop looping really fast whenever you want to drive the steppermotor in a non-blocking way. The function run() has to be called 1000 times per second to make sure that the step-pulses are created right in time.

The MobaTools create the step-pulses "in the backround" with the help of a timer.
This enables to start the stepper-motor and immitiately change over to executing other code
while the step-pulses are created with the right timing.

**Comment by ftjuh** [comment]
I think you're mostly wrong. What you're saying is that MobaTools is better suited to your particular demands. Other users have other demands, e.g. avoiding timer or interrupt conflicts.

But this is not the point here.

You submitted this repo to the library manager, so I feel it is your obligation to keep this updated. If you are not willing to do so, fine. But then pull it from the library manager, to allow other to jump in and prevent users from using an outdated library.

**Comment by waspinator** [comment]
thanks @ftjuh for reminding me to update the library. It's now at 1.64.
